name: Build server container
on:
  push:
    paths:
      - python/**
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v3

      - uses: docker/login-action@v2.2.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4.6.0
        with:
          images: ghcr.io/open-event-systems/interview-server
          tags: |
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main'  }}

      - uses: docker/build-push-action@v4.1.1
        with:
          context: python
          push: true
          tags: ${{ steps.meta.outputs.tags }}
